language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.0-preview2-003121
    - os: osx
      osx_image: xcode8.1
      mono: latest
      dotnet: 1.0.0-preview2-003121

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
before_script:
  - chmod +x ./build.sh
script:
  - dotnet --info
  - ./build.sh
